export const currentUser = {
  name: "Rajesh Kumar",
  id: "SP-847291",
  city: "Bengaluru",
  zone: "Koramangala South",
  role: "Food Delivery Partner",
  platform: "Zomato",
  trustScore: 94,
  joinedDate: "2023-04-12",
  avatar: "/avatars/worker-1.png", // Fallback generated by UI if missing
};

export const activePolicy = {
  id: "POL-BLR-2941",
  status: "Active",
  planName: "Pro Shield",
  weeklyPremium: 120, // ₹
  payoutCap: 5000,    // ₹
  renewalDate: "2026-03-24", // Next week
  earningsProtectedThisWeek: 3150,
  coveredTriggers: ["Heavy Rain", "Flood Alert", "Zone Shutdown", "AQI Spike"],
};

export const pricingPlans = [
  {
    id: "basic",
    name: "Basic Shield",
    premium: 45, // ₹/week
    payoutCap: 1500,
    features: ["Heavy Rain Coverage", "100+ AQI Alert"],
    recommended: false,
  },
  {
    id: "plus",
    name: "Shield Plus",
    premium: 85,
    payoutCap: 3000,
    features: ["Heavy Rain Coverage", "200+ AQI Alert", "Heatwave >40°C"],
    recommended: true,
  },
  {
    id: "pro",
    name: "Pro Shield",
    premium: 120,
    payoutCap: 5000,
    features: [
      "All Weather Alerts",
      "Zone Shutdowns",
      "Priority Payouts",
      "Zero Deductible",
    ],
    recommended: false,
  },
];

export const mockTriggers = [
  {
    id: "TR-01",
    type: "Heavy Rain",
    status: "Active",
    severity: "High",
    affectedZones: ["HSR Layout", "Koramangala", "BTM Layout"],
    eligibleWorkers: 4210,
    claimsTriggered: 1140,
    lastUpdated: "10 mins ago",
    trend: "+12%",
  },
  {
    id: "TR-02",
    type: "AQI Spike",
    status: "Warning",
    severity: "Medium",
    affectedZones: ["Whitefield", "Marathahalli"],
    eligibleWorkers: 2800,
    claimsTriggered: 0,
    lastUpdated: "1 hour ago",
    trend: "Stable",
  },
  {
    id: "TR-03",
    type: "Flood Alert",
    status: "Cleared",
    severity: "Low",
    affectedZones: ["Bellandur"],
    eligibleWorkers: 0,
    claimsTriggered: 450,
    lastUpdated: "Yesterday",
    trend: "-80%",
  },
  {
    id: "TR-04",
    type: "Zone Shutdown",
    status: "Active",
    severity: "Critical",
    affectedZones: ["Indiranagar (100ft Rd)"],
    eligibleWorkers: 850,
    claimsTriggered: 850,
    lastUpdated: "Just Now",
    trend: "+100%",
  },
];

export const recentClaims = [
  {
    id: "CLM-9021",
    date: "2026-03-18",
    amount: 850,
    trigger: "Heavy Rain - Koramangala",
    status: "Paid",
  },
  {
    id: "CLM-8910",
    date: "2026-03-19", // Today
    amount: 1200,
    trigger: "Zone Shutdown - Indiranagar",
    status: "Under Review",
  },
  {
    id: "CLM-7742",
    date: "2026-02-28",
    amount: 400,
    trigger: "AQI Spike > 300 - HSR",
    status: "Paid",
  },
];

export const fraudInsightsData = {
  overallRiskScore: 12, // out of 100 (Low Risk)
  totalSpoofingAttemptsPrevented: 1420,
  suspiciousClaimsTrend: [
    { day: "Mon", claims: 4, detected: 4 },
    { day: "Tue", claims: 7, detected: 6 },
    { day: "Wed", claims: 2, detected: 2 },
    { day: "Thu", claims: 15, detected: 14 },
    { day: "Fri", claims: 5, detected: 5 },
  ],
  activeThreats: [
    {
      id: "TH-1",
      type: "Coordinated Mass Claim",
      description: "Multiple devices claiming 'Zone Shutdown' from same IP block.",
      status: "Blocked",
      severity: "High",
      time: "2 hours ago",
    },
    {
      id: "TH-2",
      type: "GPS Mock Location",
      description: "Worker app reporting location in flooded zone while network IP suggests differently.",
      status: "Reviewing",
      severity: "Medium",
      time: "15 mins ago",
    },
    {
      id: "TH-3",
      type: "Route Mismatch",
      description: "Impossible movement speed detected between subsequent pings.",
      status: "Blocked",
      severity: "Low",
      time: "5 hours ago",
    },
  ],
};

export const earningsChartData = [
  { day: "Mon", earnings: 400 },
  { day: "Tue", earnings: 600 },
  { day: "Wed", earnings: 350 },
  { day: "Thu", earnings: 800 },
  { day: "Fri", earnings: 0 }, // E.g. Heavy Rain
  { day: "Sat", earnings: 0 },
  { day: "Sun", earnings: 0 },
];
